burger-menu v1
js-tasks-ru/htmlcss-20240412_easygoin2022 pull request #20
Opened 2024-05-12 08:53 UTC by simvaliant

2024-05-13 08:26 UTC, GSemikozov requested changes

2024-05-13 08:26 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-open,
.burger-menu-open - это не часть блока

2024-05-13 08:26 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-close{
по БЭМ - .burger-menu__close

2024-05-16 12:23 UTC, GSemikozov requested changes

2024-05-16 12:23 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.open-button,
.open-button - если это отдельный блок, то почему описываем его в бургер-меню?) 
в целом, надо просто удалить, триггером меню может быть любой элемент на странице

2024-05-16 13:33 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-18 13:15 UTC, GSemikozov submitted a review, later dismissed

2024-05-18 13:15 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-05-18 13:18 UTC, GSemikozov approved these changes

2024-05-18 13:18 UTC, merged