theme-changer-task
js-tasks-ru/htmlcss-20240412_easygoin2022 pull request #21
Opened 2024-05-12 11:07 UTC by simvaliant

2024-05-12 11:09 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-13 08:28 UTC, GSemikozov requested changes

2024-05-13 08:28 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler_project{
для переключателя - раз уж мы в тогл забрались - нужно создать отдельный компонент, где этот тогл будет использоваться

2024-05-14 10:33 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-14 15:49 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-14 18:42 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-16 12:24 UTC, GSemikozov approved these changes

2024-05-16 12:24 UTC, merged