added accordion
js-tasks-ru/htmlcss-20240412_easygoin2022 pull request #4
Opened 2024-04-17 15:19 UTC by simvaliant

2024-04-17 15:19 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-18 10:50 UTC, GSemikozov requested changes

2024-04-18 10:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 50%;
однозначно лишнее)

2024-04-18 10:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 1.5rem;
не по макету

2024-04-18 10:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border-radius: 10px;
8

2024-04-18 10:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    color: var(--black);
не хватает свойств для описания текста

2024-04-18 10:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    color: var(--grey-4);
не хватает свойств для описания текста

2024-04-18 10:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    color: var(--grey-4);
а еще - тут видимо отступ сверху должен быть? и паддинг снизу, это видно если .accordion__item[open]

2024-04-18 10:50 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion__item">
элементы блока не могут существовать вне блока, поэтому все секции надо завернуть в общий div с классом блока

2024-04-18 11:48 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-18 13:42 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-19 09:13 UTC, GSemikozov requested changes

2024-04-19 09:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    font-family: 'Roboto', sans-serif;
Inter

2024-04-19 10:03 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-20 07:34 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-22 14:45 UTC, GSemikozov requested changes

2024-04-22 14:45 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap');
шрифты подключаем в fonts.css

2024-04-22 14:45 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion *{
не нужен здесь `*`))

2024-04-22 14:45 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border: 2px solid var(--black);
1px

2024-04-25 16:12 UTC, GSemikozov requested changes

2024-04-25 16:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border: 2px solid var(--black);
все еще актуально

2024-04-26 07:14 UTC, GSemikozov approved these changes

2024-04-26 07:14 UTC, merged