Macro layout
js-tasks-ru/htmlcss-20240412_easygoin2022 pull request #5
Opened 2024-04-20 11:41 UTC by simvaliant

2024-04-20 11:41 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-20 11:43 UTC, simvaliant commented on components/card/card.css
inline-block случайно оставил. В следующем коммите уберу тогда

2024-04-20 11:45 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-25 16:21 UTC, GSemikozov requested changes

2024-04-25 16:21 UTC, GSemikozov commented on components/card/card.css
> +.card p{
.card__title

2024-04-25 16:21 UTC, GSemikozov commented on components/card/card.css
> +    margin-bottom: 30px;
лучше паддинги на уровне блока

2024-04-25 16:21 UTC, GSemikozov commented on components/footer/footer.css
> +.footer *{
судя по тому что это повторяется во всех ПР-ах - договоримся о таком правиле: вообще не использовать `*` )

2024-04-25 16:21 UTC, GSemikozov commented on components/footer/footer.css
> +    margin-top: -24px;
а зачем отрицательный марджин?

2024-04-25 16:21 UTC, GSemikozov commented on components/footer/footer.css
> +    width: 640px;
max-width

2024-04-25 16:21 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap');
в fonts.css.

в марках этого ПР-а проверяем аккордион?

2024-04-29 10:59 UTC, GSemikozov approved these changes

2024-04-29 10:59 UTC, merged