histogram 1st commit
js-tasks-ru/htmlcss-20240412_easygoin2022 pull request #6
Opened 2024-04-22 08:35 UTC by simvaliant

2024-04-22 08:39 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-22 10:16 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-22 14:47 UTC, GSemikozov requested changes

2024-04-22 14:47 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
не нужно ограничивать ширину и высоту

2024-04-22 14:47 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
зато не хватает общих паддингов

2024-04-22 14:47 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0 24px;
чтобы потом на уровне каждого доч элемента не задавать такие марджины

2024-04-22 14:47 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__upper *{
не используем `*`

2024-04-22 14:47 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.orders p{
и вложенные селекторы и селекторы тегов в БЭМ тоже не используем. Ниже - то же самое

2024-04-22 14:47 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.bar:first-child{
нет) либо 3 модификатора элемента с 3 разными высотами, либо просто инлайним

2024-04-22 14:47 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.bar{
это же элемент блока, а не отдельный блок, то есть например .histogram__chart

2024-04-23 07:20 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-23 10:49 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-26 07:15 UTC, GSemikozov approved these changes

2024-04-26 07:15 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-04-26 07:17 UTC, GSemikozov approved these changes

2024-04-26 07:17 UTC, merged